# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-15 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('realname', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=128)),
                ('days', models.CharField(max_length=128)),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
            ],
        ),
    ]
