# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-14 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=128)),
                ('days', models.CharField(max_length=128)),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacate.Event')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='guest',
            unique_together=set([('event', 'realname')]),
        ),
    ]
